### ISSUE TITLE
Google Analytics Plugin Not Working

### ISSUE THREAD

**Issue by wootwoot1234** [purplecabbage/phonegap-plugins#29]
Google Analytics Plugin isn't working with the latest phonegap (1.0 rc1/2).  I would love to add this to my apps.  Please fix it!  :)

**Comment by shazron** [comment]
Wrong repo, that plugin does not even exist here. File it at phonegap/phonegap-plugins, the official repo

**Comment by akougblenou** [comment]
Hi,

I have just recemtly got interested in the Google Analytics plugin but found out since it has been released in may it has been destroyed, discontinued and just recently reinstated.

While it works like a charm for Android it does not for iOS.

As my knowledge of objective C is quite limited I was wondering if an update was in planning... 
I got to solve most of the bug but (outdated way to do an import) I am still getting this error : 

Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_GANTracker", referenced from:
      objc-class-ref in GoogleAnalyticsPlugin.o
ld: symbol(s) not found for architecture i386
collect2: ld returned 1 exit status

can someone help please ?

**Comment by wootwoot1234** [comment]
That sounds like an error I got.  Make sure you're adding the plugins
correctly.  It does work on iOS.  The instructions for installation are not
great and you need to make a few changes to make it work with the new plugin
format but it works.

Tom

**Comment by akougblenou** [comment]
Okay would you mind explaining to me how did you get it to work and what did you actually changed  ?

**Comment by wootwoot1234** [comment]
It's been a while since I had the error and I'm also pretty new to xcode.

I think this is what I did wrong.

Make sure that you've added the plugin files as a "_group_" (_yellow folder_)
not as a "_folder reference_" (_blue folder_). Just delete the reference and
re-add it if you made a mistake.

Here's more trouble shooting info.

http://wiki.phonegap.com/w/page/41733808/PhoneGap%20iOS%20Plugins%20Problems

**Comment by akougblenou** [comment]
Thanks, I have other issue on it now but at least it is compiling

**Comment by Ruddiger** [comment]
For anyone still looking for answers. this beautiful person has combined instructions...

http://stackoverflow.com/questions/8097015/step-by-set-to-get-google-analytics-working-in-phonegap-1-2-0-on-ios-phonegapal
