### ISSUE TITLE
AudioRecord is not working in 1.7.0

### ISSUE THREAD

**Issue by chohome** [purplecabbage/phonegap-plugins#85]
hi!
If run in 1.7.0, error message is shown

[INFO] Error in success callback: File2 = TypeError: 'undefined' is not a function

how to solve this problem? 

peace.
